name: Test-create and publish Docker images

on:
  push:
    paths:
      - Dockerfile
      - '*.Dockerfile'
      - .github/workflows/upload-ghcr.yaml

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Check out source
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push regular image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/jj/raku-zef

      - name: Build and push github actions image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: github-actions.Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/jj/raku-zef-gha

      - name: Build and push github actions + coverage image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: github-actions-coverage.Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/jj/raku-racoco-gha
