name: Create and push to GHCR a multiarch image

on:
  push:
    paths:
      - multiarch.Dockerfile
      - .github/workflows/upload-ghcr-multiarch.yaml

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Log in to GHCR
        uses: docker/login-action@v1.10.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: QEMU is needed for multiarch
        uses: docker/setup-qemu-action@master
        with:
          platforms: all

      - name: Set up Docker Buildx for multiarch
        id: buildx
        uses: docker/setup-buildx-action@master
        with:
          driver-opts: env.BUILDKIT_STEP_LOG_MAX_SIZE=10485760

      - name: Build and push to GHCR
        uses: docker/build-push-action@v2.10.0
        with:
          push: true
          file: ./Dockerfile
          platforms: linux/arm/v7,linux/ppc64le,linux/arm64/v8
          tags: ${{ env.REGISTRY }}/jj/raku-zef-multiarch


